# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignUp_App.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignUp_MainWinodow(object):
    def setupUi(self, SignUp_MainWinodow):
        SignUp_MainWinodow.setObjectName("SignUp_MainWinodow")
        SignUp_MainWinodow.resize(1053, 726)
        self.centralwidget = QtWidgets.QWidget(SignUp_MainWinodow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(210, 130, 631, 411))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.LE_UserName = QtWidgets.QLineEdit(self.widget)
        self.LE_UserName.setObjectName("LE_UserName")
        self.horizontalLayout.addWidget(self.LE_UserName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.LE_Password = QtWidgets.QLineEdit(self.widget)
        self.LE_Password.setObjectName("LE_Password")
        self.horizontalLayout_2.addWidget(self.LE_Password)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.LE_PhoneNumber = QtWidgets.QLineEdit(self.widget)
        self.LE_PhoneNumber.setObjectName("LE_PhoneNumber")
        self.horizontalLayout_3.addWidget(self.LE_PhoneNumber)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.LE_Mail = QtWidgets.QLineEdit(self.widget)
        self.LE_Mail.setObjectName("LE_Mail")
        self.horizontalLayout_4.addWidget(self.LE_Mail)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.btn_Enroll = QtWidgets.QPushButton(self.widget)
        self.btn_Enroll.setObjectName("btn_Enroll")
        self.verticalLayout.addWidget(self.btn_Enroll)
        SignUp_MainWinodow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SignUp_MainWinodow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1053, 23))
        self.menubar.setObjectName("menubar")
        SignUp_MainWinodow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SignUp_MainWinodow)
        self.statusbar.setObjectName("statusbar")
        SignUp_MainWinodow.setStatusBar(self.statusbar)

        self.retranslateUi(SignUp_MainWinodow)
        QtCore.QMetaObject.connectSlotsByName(SignUp_MainWinodow)

    def retranslateUi(self, SignUp_MainWinodow):
        _translate = QtCore.QCoreApplication.translate
        SignUp_MainWinodow.setWindowTitle(_translate("SignUp_MainWinodow", "MainWindow"))
        self.label.setText(_translate("SignUp_MainWinodow", "用户名"))
        self.label_2.setText(_translate("SignUp_MainWinodow", "密码"))
        self.label_3.setText(_translate("SignUp_MainWinodow", "手机号"))
        self.label_4.setText(_translate("SignUp_MainWinodow", "邮箱"))
        self.btn_Enroll.setText(_translate("SignUp_MainWinodow", "确认注册"))
